### ISSUE TITLE
Trailing White Spaces in Requester Name Causes Misleading Results

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#7]
It looks like TO.db sometimes contains Requester Names with trailing white spaces in the name that can generate misleading results.

Example:
todbreader  - "Webis " search for Requester Name is not equal to "Webis"

Also, searching for Requester ID A7W013PM199BS does not show the review with a tailing space.

**Comment by toutils** [comment]
I'm looking at this, this is what TO displays at least in this case. 
If you search TO for "Webis " (with the space), it shows the review, and the html does actually have the space. 
`<a href="/reports?id=A7W013PM199BS">Webis </a>`
while all the other reviews do not
`<a href="/reports?id=A7W013PM199BS">Webis</a>`

The relevant line in todbmanager:
https://github.com/toutils/todbmanager/blob/4b6332e222af0af22c28dbbc7170b6107e647209/toscraper.py#L145

This trims newlines, but doesn't trim spaces. Apparently TO doesn't trim spaces either. It seems like that's what the reviewer typed in. 

> Also, searching for Requester ID A7W013PM199BS does not show the review with a tailing space.

I see this review, it's back on page 3 on the release database using todbreader, and I see it on TO both when searching for the requester id using the search function, and on the requester page https://turkopticon.ucsd.edu/reports?id=A7W013PM199BS&page=2. When searching using a requester  name, it shows on both "Webis" and "Webis " searches, so TO is either dropping the space in the search or doing some kind of fuzzy string search on the search field for requester names/ids. 

Looking at todbreader, it displays the space in the requester name field using both requester id and requester name searches, everything seems fine there. Todbreader doesn't trim spaces either, it only trims newlines from back when that was a problem with todbmanager, when it was including newlines in the database. Eventually that part should be removed, trailing/leading newlines shouldn't be in the database in the first place now. 

Looking at the duplicate checking code it shouldn't be a problem, duplicates are checked based on requester_id and user_id, requester_name isn't a factor anywhere. 

I don't think this is a problem, everything seems to be doing what it's supposed to; it's the behavior that's unexpected. Todbreader should probably have an option to do a fuzzy string search instead of an exact search for a requester name, the reason it doesn't is because it's expensive processing wise, and if it's done in sqlite it would require full text search tables, which is again expensive processing wise and would require a new database version to add full text search tables.

**Comment by toutils** [comment]
I think the decision here is whether or not the TO database todbmanager generates should deviate from TO in this case, by trimming spaces from requester names. Arguably it already does deviate by trimming newlines all over the place, but that's slightly different, it's doing it to clean up the results of the scraper. The original review/comment content probably didn't have it either, though if someone did write a review/comment with 10 newlines before any content, todbmanager would trim it out. 

In this case I don't think it should deviate. If there's a leading/trailing space in the requester name on TO, it should probably reflect in the database, with the answer being adding fuzzy search in todbreader or anything else reading the database. If you search TO for "Webis " ( with the space ), it does produce different results, clearly that is what TO has recorded for the requester name.

**Comment by rtayne** [comment]
After looking at more examples in both TO edu and to.db, I came to the same conclusion that trailing white spaces should be reflected in the to.db. 

Entries with trailing white spaces are "same requester_id, different requester_name" type entries just like they would be if a requester changed their requester_name over time.

**Comment by toutils** [comment]
Thinking about it that's not how the multiple reviews by a single reviewer on a single requester id issue was handled. 
https://turkopticon.ucsd.edu/forum/show_post/1839
I switched the new/modified/existing review checking away from the review_id in that case and instead used requester_id + user_id, which meant that only one of the multiple reviews would be included in the database. 
I should probably switch it back to using just the review_id. It's a bug with TO but there are cases where a single reviewer was able to review a requester multiple times; it's in the TO database, it should be in the database todbmanager generates.

**Comment by rtayne** [comment]
Interesting bug. It looks like the Review was submitted on March 8 and edited on March 11. I noticed that the Daylight Savings Time occurred on March 10.  If more of these exist, I wonder if they occur near dates where time changes are implemented.

**Comment by toutils** [comment]
I haven't tried to test any of this, it's just a theory; but I think it's due to a script or program someone is using which is implementing review posting inside of the script/app, bypassing TO's front-end. Either way I think I'm going to switch it back over before I post next month's review database. In that case it's going to look like there's some duplicate's in the database in some cases, but they will have unique review_id's and it should mirror what is in TO.

**Comment by toutils** [comment]
I'm gonna close this since it isn't actually a bug. The scraper is functioning as it should.
