### ISSUE TITLE
Discrepancy in Requester Name with an Escape Character

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#8]
Not really an issue, but I noticed when I do an HTTP request for:
https://turkopticon.ucsd.edu/api/multi-attrs.php?ids=A3DUTV8ON94ZGX 

the response has an escape character in the requester name:

{"A3DUTV8ON94ZGX":{"name":"Christian Tr\u00f6ster","attrs":{"comm":"4.75","pay":"4.08","fair":"4.81","fast":"4.88"},"reviews":70,"tos_flags":1}}

The stats table in to.db does not have the escape character:
"Christian Tröster"

**Comment by toutils** [comment]
Relevant line:
https://github.com/toutils/todbmanager/blob/3b9e37bddaeee73bcdb6fa2bc56121b0e6817c29/toscraper.py#L145

The line above should be the only modification to the requester name before it get's gets sent to sqlite to write. Python3 is all unicode and so is sqlite. I think the data here is the same, it's just a matter of how it is being displayed. The database still has the right character, because it's all unicode, but the data isn't being saved in json format with the \u notation in ascii characters, it's written to the table in unicode. 

If something is using this database and returning json, (an api), it's going to have to convert all this to json anyway, and in the process it should convert the string to the \u notation.  

It could probably be converted to this but I think it would just create a headache for anyone using it.

**Comment by rtayne** [comment]
Yes very good, and thank you for the explanation. It can all be confusing at times. Here is another example for requesterid A3OKC5SI2SMS8S:

The HTTP request from mturk (&format=json) returned Content-Type: application/json; charset=utf-8 and the requester_name : "Sinué Salgado" was displayed.

The HTTP request from https://turkopticon.ucsd.edu/api/multi-attrs.php?ids=A3OKC5SI2SMS8S returned Content-Type: text/html and displayed "name":"Sinue Salgado", with no \u notation.  Also from the TO reports pages and todbreader, it appears to be stored as both "Sinué Salgado" and "Sinue Salgado".

Exactly how TO decides which name to display in the api/multi-attrs.php page is a mystery to me and perhaps to you too.

Again, thank you for your time.

**Comment by toutils** [comment]
> Exactly how TO decides which name to display in the api/multi-attrs.php page is a mystery to me and perhaps to you too.

I'm sure it's in the TO source code somewhere, but it's a similar issue to what is being saved as the requester name in the stats table in the database here; when a requester id has multiple requester names. 

As far as how todbmanager handles it, it's whatever the last row inserted was. This probably isn't the best behavior because it's going to change depending on when the stats table is generated. There's 2 cases here with different behavior.
- Case 1: fresh scrape: Requester name will be the name of the very earliest review for the requester (TO pages are sorted last to first). The behavior should be the same for both the -nostats option with the stats table generated afterward and without it with it being updated every time. 
- Case 2: update scrape, stats updated normally (regenerated on every review): The last row at this point will be the last *new* review from the scrape for that requester id. If two *new* reviews for a specific requester id come in and the modification scrape picked up 5 pages, say one on page 1, and another on page 4 for that requester id, then the last review inserted would be the one on page 4. 

Thinking about all of this; this seems dumb. The database has date data. The requester name should be based either on that (the actual latest review based on date, not the last row inserted). It could count the number of occurrences and use whatever is used more, but some requesters change their name often and that probably won't be accurate as far as what it currently is. 

Alternatively in an effort to have this be as close of a mirror to TO as possible I could dig through the TO source code and try to figure out how it's being done there; and try to match that.
